name: jell_mpv_dart
description: Jellyfin playback shim that relays Jellyfin sessions to an mpv player.
version: 0.1.0
repository: https://github.com/example/jell-mpv-dart

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  retry: ^3.1.2
  talker: ^4.6.14
  uuid: ^4.5.0
  web_socket_channel: ^2.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.0.0
